FROM python:3.8-buster
RUN pip install dask-cloudprovider[aws]==2021.3.1 
RUN pip install prefect[aws]==0.14.13
RUN pip install xarray
RUN pip install zarr
RUN pip install s3fs
RUN pip install git+https://github.com/pangeo-forge/pangeo-forge
RUN pip install h5py
RUN pip install h5netcdf
