FROM python:3.8-buster
# RUN pip install  botocore==1.19.52 dask-cloudprovider==2021.3.1  boto3==1.9
RUN pip install dask-cloudprovider[aws]==2021.3.1 
# RUN pip install boto3==1.16.52
RUN pip install prefect[aws]==0.14.13
